spring.datasource.url: jdbc:sqlserver://localhost;databaseName=sample
spring.datasource.username: sa
spring.datasource.password: admin123
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto: update

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace